modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/SteveKunG/SkyBlockcatia/issues"
license = "MIT License"

[[mods]]
modId = "skyblockcatia"
version = "${version}"
displayName = "SkyBlockcatia"
description = "Useful Hypixel Skyblock features, QOL and In-game API Viewer!"
credits = "Credit to LeaPhant, matdoes for inspiration to make In-game API Viewer possible"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/skyblockcatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/skyblockcatia_version.json"
authors = "SteveKunG"
logoFile = "logo.png"

[[dependencies.skyblockcatia]]
modId = "forge"
mandatory = true
versionRange = "[37.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.skyblockcatia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.skyblockcatia]]
modId = "architectury"
mandatory = true
versionRange = "[2.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.skyblockcatia]]
modId = "stevekungs_lib"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.skyblockcatia]]
modId = "indicatia"
mandatory = false
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "CLIENT"