modLoader="javafml"
loaderVersion="[31,)"
updateJSONURL="https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/skyblockcatia_version.json"
issueTrackerURL="https://github.com/SteveKunG/SkyBlockcatia/issues"

[[mods]]
modId="skyblockcatia"
version="2.0.0"
displayName="SkyBlockcatia"
description="Useful Hypixel Skyblock features, QOL and In-game API Viewer!"
credits="Credit to LeaPhant, matdoes for inspiration to make In-game API Viewer possible"
displayURL="https://minecraft.curseforge.com/projects/skyblockcatia"
authors="SteveKunG"
logoFile="logo.png"

[[dependencies.skyblockcatia]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[3.0.8,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="indicatia"
    mandatory=false
    versionRange="[3.0.6,)"
    ordering="NONE"
    side="CLIENT"